name: X86-OpenWrt

on:
#  schedule:
#    - cron: 5 6 * * 0
  workflow_dispatch:
    inputs:
      upload_source:
        description: "Upload source folder before build"
        required: false
        type: boolean
        default: false
      build_firmware:
        description: "Build and publish firmware"
        required: false
        type: boolean
        default: true
      badge_status:
        description: "badge status var（keep empty）"
        required: false
        type: string
        default: ''
  watch:
    types: started

jobs:
  build:
    uses: ./.github/workflows/OpenWrt-Matrix.yml
    if: github.event.repository.owner.id == github.event.sender.id && inputs.badge_status == ''
    with:
      targets: "X86"
      upload_source: ${{ github.event_name == 'workflow_dispatch' && inputs.upload_source }}
      build_firmware: ${{ (github.event_name == 'workflow_dispatch' && inputs.build_firmware) || github.event_name != 'workflow_dispatch' }}

  sync_badge:
    if: inputs.badge_status != ''
    runs-on: ubuntu-latest
    steps:
      - name: Sync badge status
        run: |
          echo "Syncing badge status ...( ${{ inputs.badge_status }} )"
          if [ "${{ inputs.badge_status }}" == "success" ]; then
            exit 0
          else
            exit 1
          fi
